FROM python:3.9-bullseye
COPY repositories /etc/apk/repositories
RUN apt-get update
RUN pip install --upgrade pip
RUN apt-get install -y python3-opencv
RUN apt-get install -y openssl
WORKDIR /app
COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip pip3 install --no-cache-dir -r /app/requirements.txt
RUN --mount=type=cache,target=/root/.cache/models python3 -m spacy download en_core_web_trf
COPY . /app
ENTRYPOINT ["python3"]
CMD ["/app/main_process.py"]